### ISSUE TITLE
DefaultLdapEntryManager find

### ISSUE THREAD

**Issue by sysmat** [vt-middleware/ldaptive#50]
I have user in LDAP(389 Directory Server) whith attribute nsAccountLock, but when I perform find with manager I get all attributes except nsAccountLock from LDAP.

Bean:
---------
@Attribute(name = "nsAccountLock", property = "lock")

If I use SearchRequest without naming attributes I don't get nsAccountLock attribute, but if I explicitly  define in search result then I get it.

But in find dosen't get it, what I'm doing wrong?

Regards, Tomaz

**Comment by sysmat** [comment]
nsAccountLock atribut is DIRECTORY_OPERATION maybe there is a problem.

So find implementations do search something like that attrs=ALL or explicitly by @Attribute annotations in bean?

Regards, Tomaž

**Comment by sysmat** [comment]
Another question is how to handled multi valued attribute with manager and merge function.
Especially how to remove attribute or my explicitly use  ModifyOperation and ModifyRequest

Regards, Tomaz

**Comment by dfish3r** [comment]
Which version are you using and can you try out the last snapshot?

**Comment by sysmat** [comment]
Latest version(downloded today 2015-07-14) and  nsAccountLock(operational attribute) atribut not mapped

**Comment by dfish3r** [comment]
Tryout the snapshot, I feel like this has been fixed:

https://github.com/vt-middleware/maven-repo/blob/master/org/ldaptive/ldaptive/1.1.0-SNAPSHOT/ldaptive-1.1.0-20150714.175201-2.jar

**Comment by sysmat** [comment]
Maybe I'm doing something wrong.
1) I download ldaptive-master.zip
2) I deployed as snapshot in my local nexus
3) Run application with latest snapshot

UserLdap Bean:
------
....
@Attribute(name = "nsAccountLock", property = "nsAccountLock"),   
@Attribute(name = "objectClass", values = {"top","person","inetOrgPerson","organizationalPerson","posixAccount","shadowAccount","eduPerson"
                                                ,"schacContactLocation","schacEmployeeInfo","schacEntryConfidentiality","schacEntryMetadata"
                                                ,"schacLinkageIdentifiers","schacLinkageIdentifiers","schacPersonalCharacteristics","schacUserEntitlements"})
...
...
private String[] nsAccountLock = new String[0];
...
public String[] getNsAccountLock() {
        return nsAccountLock;
    }
    public void setNsAccountLock(String[] nsAccountLock) {
        this.nsAccountLock = nsAccountLock;
    }
--------

main class:
--------------
UserLdap user = new UserLdap("mcadez@guest.arnes.si");           
DefaultLdapEntryMapper mapper = new DefaultLdapEntryMapper();
DefaultLdapEntryManager manager = new DefaultLdapEntryManager(mapper, connFactory);            
result = (UserLdap) manager.find(user);                  

result:
------
UserLdap{distinguishedName=eduPersonPrincipalName=mcadez@guest.arnes.si,dc=guest,dc=arnes,dc=si;
 eduPersonPrincipalName=mcadez@guest.arnes.si;
 commonName=Mojca Cadez;
 group=9999;
 homeDirectory=/out/50/testko909;
 surname=Cadez;
 username=mcadez;
 unixUniqueNumber=31593;
 gecos=BlaBla5;
 shadowExpire=16741;       
------

Attribute nsAccountLock is empty but in LDAP is set to nsAccountLock=true and with search I get it.

Regards, Tomaz

**Comment by sysmat** [comment]
My Ldap is 389 Directory Server version centos-ds-8.2.0-2.el5.centos

nsAccountLock is DIRECTORY_OPERATION aka operational attribute and server will NOT return it if not explicitly  defined in request.

Regards, Tomaz

**Comment by sysmat** [comment]
And in my LDAP log:

Jul 15 10:26:10 morez centosds-access [15/Jul/2015:10:25:38 +0200] conn=1062 fd=81 slot=81 connection from 193.2.1.179 to 193.2.18.199
Jul 15 10:26:10 morez centosds-access [15/Jul/2015:10:25:38 +0200] conn=1062 op=0 BIND dn="eduPersonPrincipalName=root@guest.arnes.si,dc=guest,dc=arnes,dc=si" method=128 version=3
Jul 15 10:26:10 morez centosds-access [15/Jul/2015:10:25:38 +0200] conn=1062 op=0 RESULT err=0 tag=97 nentries=0 etime=0 dn="edupersonprincipalname=root@guest.arnes.si,dc=guest,dc=arnes,dc=si"
Jul 15 10:26:10 morez centosds-access [15/Jul/2015:10:25:38 +0200] conn=1062 op=1 SRCH base="eduPersonPrincipalName=mcadez@guest.arnes.si,dc=guest,dc=arnes,dc=si" scope=0 filter="(objectClass=*)" attrs="* + aci"
Jul 15 10:26:10 morez centosds-access [15/Jul/2015:10:25:38 +0200] conn=1062 op=1 RESULT err=0 tag=101 nentries=1 etime=0
Jul 15 10:26:10 morez centosds-access [15/Jul/2015:10:25:38 +0200] conn=1062 op=2 UNBIND
Jul 15 10:26:10 morez centosds-access [15/Jul/2015:10:25:38 +0200] conn=1062 op=2 fd=81 closed - U1

**Comment by dfish3r** [comment]
I'm still not certain you're running the latest version.
I think this bug was fixed here:
https://github.com/vt-middleware/ldaptive/commit/41706d42d8bbb4b625f52047662d5352de70760c#diff-f8691fe6607c2cc207e59541fa48e524
Which would include all operational attributes by default.

Please make sure you're using this version:
https://github.com/vt-middleware/maven-repo/blob/master/org/ldaptive/ldaptive/1.1.0-SNAPSHOT/ldaptive-1.1.0-20150714.175201-2.jar?raw=true
Or build the latest version from the master branch.

**Comment by dfish3r** [comment]
You can perform a simple test from the command line which mimics the search:
```sh
ldapsearch -H ldap://my.directory.org:389 -x \
-b 'eduPersonPrincipalName=mcadez@guest.arnes.si,dc=guest,dc=arnes,dc=si' \
-s base '(objectClass=*)' '*' '+'
```

If that search does not return the attribute you're locking for, then I'll have to provide some way for you to inject attribute names into the `LdapEntryManager` so they can be added to search.

**Comment by sysmat** [comment]
As I understand  Ldap(389 Directory Serve) for returning operational attributes they should be explicitly requested.

http://directory.fedoraproject.org/docs/389ds/howto/howto-operationalattributes.html

I though that manager 'scan' attributes in annotation @Entry and adding them in request

Regards, Tomaž

**Comment by dfish3r** [comment]
Sounds like this particular directory server does not support the plus (+) syntax for returning all operational attributes.

I'll add support for specifying attribute names to be included in the search.

**Comment by dfish3r** [comment]
Fixed in https://github.com/vt-middleware/ldaptive/commit/c26c6513865a8ff0eb97db5576579695c786dffb
